name: caltalyze

services:
  backend:
    build: ./backend
    networks:
      - caltalyze
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GEMINI_MODEL=${GEMINI_MODEL}
      - OLLAMA_MODEL=${OLLAMA_MODEL}

networks:
  caltalyze: